title: Pyblog
description: Pyblog 是一个简单易用的在线 Markdown 博客系统，它使用 Python 的 flask 架构，理论上支持所有 flask-sqlalchemy 所能支持的数据库。 编辑器使用的是  editor.md。最新的版本支持且仅支持python3！ Python 的 Markdown to HTML 编译器使用的是 Mistune！ Just so！ 
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
